add environment variable warning

diff --git a/bin/ch-test b/bin/ch-test
--- a/bin/ch-test
+++ b/bin/ch-test
@@ -4,23 +4,47 @@ libexec="$(cd "$(dirname "$0")" && pwd)"
 . "${libexec}/base.sh"
 . "${libexec}/version.sh"
 
-# shellcheck disable=SC2034
-usage=$(cat <<EOF
-Run the Charliecloud test suite.
+check_env () {
+    if [[ -n $2 ]]; then
+        printf "prefix: warning: %s set and will be used\n" "$1"
+    fi
+}
 
-Usage:
+fatal () {
+    printf '%s\n\n' "$1" 1>&2
+    exit 1
+}
 
-  $ $(basename "$0") [ARGS ...] PHASE
+perm_dirs () {
+    # TODO: skip if user can't sudo
+    [[ ! $CH_TEST_PERMDIRS = 'skip' ]] || return 0
+    printf '\nFile permission enforcement tests:\n'
+    for d in $CH_TEST_PERMDIRS; do
+        if [[ -d $d ]]; then
+            # prevent the test suite from failing if the perm_dirs directory
+            # exists
+            if [[ -d "${d}/perms_test" ]]; then
+                printf "%s/perms_test exists. removing...\n" "$d"
+                sudo rm -rf "${d}/perms_test"
+            fi
+        else
+            echo "permission directory target $d doesn't exist, creating it..."
+            mkdir -p "$d"
+        fi
+    done
+    echo
+    for d in $CH_TEST_PERMDIRS; do
+        sudo ./make-perms-test "$d" "$USER" nobody
+    done
+}
 
-You must have the charliecloud test suite installed.
-EOF
-)
-
-parse_basic_args "$@"
-
-if [ "$#" -lt 1 ]; then
-    usage
-fi
+print_info () {
+    printf '\nrunning tests from:     %s\n' "$testdir"
+    printf 'CH_TEST_SCOPE           %s\n' "$CH_TEST_SCOPE"
+    printf 'CH_TEST_TARDIR          %s\n' "$CH_TEST_TARDIR"
+    printf 'CH_TEST_IMGDIR          %s\n' "$CH_TEST_IMGDIR"
+    echo "CH_TEST_PERMDIRS        ${CH_TEST_PERMDIRS[@]}"
+}
 
 set_vars () {
     [[ -n $prefix ]]           || prefix=/var/tmp
@@ -41,33 +65,6 @@ set_vars () {
         [[ -d $CH_TEST_TARDIR ]]   || mkdir -p "$CH_TEST_TARDIR"
         [[ -d $CH_TEST_IMGDIR ]]   || mkdir -p "$CH_TEST_IMGDIR"
     fi
-}
-
-fatal () {
-    printf '%s\n\n' "$1" 1>&2
-    exit 1
-}
-
-perm_dirs () {
-    [[ ! $CH_TEST_PERMDIRS = 'skip' ]] || return 0
-    for d in $CH_TEST_PERMDIRS; do
-        if [[ -d $d ]]; then
-            # prevent the test suite from failing if the perm_dirs directory
-            # exists
-            [[ ! -d "${d}/perm_dirs" ]] || rm -rf "${d}/perm_dirs"
-        fi
-    done
-    for d in $CH_TEST_PERMDIRS; do
-        sudo ./make-perms-test "$d" "$USER" nobody
-    done
-}
-
-print_info () {
-    printf 'running tests from:     %s\n' "$testdir"
-    printf 'CH_TEST_SCOPE           %s\n' "$CH_TEST_SCOPE"
-    printf 'CH_TEST_TARDIR          %s\n' "$CH_TEST_TARDIR"
-    printf 'CH_TEST_IMGDIR          %s\n' "$CH_TEST_IMGDIR"
-    echo "CH_TEST_PERMDIRS        ${CH_TEST_PERMDIRS[@]}"
 }
 
 topdir=${ch_bin%/bin}
@@ -91,6 +88,24 @@ elif [[ ${PWD##*/} == test ]] \
     testdir=$PWD
 fi
 
+# shellcheck disable=SC2034
+usage=$(cat <<EOF
+Run the Charliecloud test suite.
+
+Usage:
+
+  $ $(basename "$0") [ARGS ...] PHASE
+
+You must have the charliecloud test suite installed.
+EOF
+)
+
+parse_basic_args "$@"
+
+if [ "$#" -lt 1 ]; then
+    usage
+fi
+
 cd "$testdir" || fatal 'cannot cd into the test directory'
 
 # Parse arguments
@@ -109,6 +124,10 @@ while [[ $# -gt 0 ]]; do
         else
             prefix=$1; shift
         fi
+        check_env 'CH_TEST_TARDIR'   "$CH_TEST_TARDIR"
+        check_env 'CH_TEST_IMGDIR'   "$CH_TEST_IMGDIR"
+        check_env 'CH_TEST_PERMDIRS' "$CH_TEST_PERMDIRS"
+        check_env 'CH_TEST_SCOPE'    "$CH_TEST_SCOPE"
     ;;
     -s|--scope=*)
         [[ -z $scope ]] || fatal 'scope: assigned more than once'
@@ -174,15 +193,20 @@ case $phase in
         make test-test
     ;;
     clean)
-        echo 'removing CH_TEST_TARDIR...'
+    if [[ -z $summary ]]; then
+        echo "removing CH_TEST_TARDIR ($CH_TEST_TARDIR)..."
         rm -rf "$CH_TEST_TARDIR"
-        echo 'removing CH_TEST_IMGDIR...'
+        echo "removing CH_TEST_IMGDIR ($CH_TEST_IMGDIR)..."
         rm -rf "$CH_TEST_IMGDIR"
-        echo 'removing CH_TEST_PERMDIRS...'
+        echo "removing CH_TEST_PERMDIRS ($CH_TEST_PERMDIRS)..."
         for d in $CH_TEST_PERMDIRS; do
-            if [[ -d ${d}/perm_dirs ]]; then
-                rm -rf "${d}/perm_dirs"
-            fi
+            [[ ! -d ${d}/perms_test ]] || rm -rf "${d}/perm_dirs"
         done
+    else
+        echo "summary mode: clean phase targets:"
+        echo "$CH_TEST_TARDIR"
+        echo "$CH_TEST_IMGDIR"
+        echo "$CH_TEST_PERMDIRS"
+    fi
     ;;
 esac
